-- Seed Tourism Experiences
-- This migration adds sample tourism experiences for testing

-- Insert sample tourism experiences
INSERT INTO public.tourism_experiences (
  name,
  slug,
  description,
  tourism_category_id,
  experience_type,
  duration,
  difficulty_level,
  group_size_min,
  group_size_max,
  age_requirement,
  region_id,
  location_details,
  meeting_point,
  whatsapp_number,
  phone,
  email,
  website,
  operator_name,
  operator_license,
  price_from,
  price_notes,
  includes,
  excludes,
  available_months,
  best_season,
  booking_required,
  advance_booking_days,
  is_verified,
  is_featured,
  is_tourism_authority_approved,
  accessibility_info,
  safety_requirements,
  what_to_bring,
  languages,
  tags
) VALUES
-- Kaieteur Falls Day Trip
(
  'Kaieteur Falls Day Trip',
  'kaieteur-falls-day-trip',
  'Experience the world''s largest single-drop waterfall on this unforgettable day trip. Fly over pristine rainforest and witness the 741-foot cascade of Kaieteur Falls, five times higher than Niagara Falls.',
  (SELECT id FROM tourism_categories WHERE slug = 'nature-wildlife'),
  'tour',
  'Full Day',
  'easy',
  2,
  12,
  'All ages',
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Kaieteur National Park, Potaro-Siparuni Region',
  'Ogle International Airport, Georgetown',
  '5926215555',
  '5926215555',
  'info@kaietourtours.gy',
  'www.kaietourtours.gy',
  'Kaietour Adventures',
  'GTA-2024-001',
  45000,
  'Per person',
  'Round-trip flight from Georgetown, Park entrance fees, Guided tour, Light refreshments',
  'Lunch, Personal expenses, Tips',
  ARRAY['Year-round'],
  'Dry season (September - April)',
  true,
  3,
  true,
  true,
  true,
  'Moderate walking required at the falls. Not wheelchair accessible.',
  'Follow guide instructions. Stay on marked paths.',
  ARRAY['Camera', 'Sunscreen', 'Hat', 'Water bottle', 'Light jacket'],
  ARRAY['English', 'Portuguese'],
  ARRAY['nature', 'photography', 'iconic', 'must-see', 'waterfall']
),

-- Iwokrama Canopy Walkway Adventure
(
  'Iwokrama Canopy Walkway Adventure',
  'iwokrama-canopy-walkway',
  'Walk among the treetops on a series of suspension bridges 30 meters above the forest floor. Spot exotic birds, monkeys, and experience the rainforest from a unique perspective.',
  (SELECT id FROM tourism_categories WHERE slug = 'adventure'),
  'activity',
  '3 hours',
  'moderate',
  1,
  15,
  '12+',
  (SELECT id FROM regions WHERE slug = 'essequibo'),
  'Iwokrama International Centre for Rainforest Conservation',
  'Iwokrama River Lodge',
  '5926775555',
  '5926775555',
  'canopy@iwokrama.org',
  'www.iwokrama.org',
  'Iwokrama International Centre',
  'GTA-2024-002',
  8500,
  'Per person',
  'Canopy walkway access, Safety equipment, Expert guide, Wildlife spotting',
  'Transportation to Iwokrama, Meals, Accommodation',
  ARRAY['Year-round'],
  'Dawn and dusk for best wildlife viewing',
  true,
  1,
  true,
  true,
  false,
  'Good physical fitness required. Not suitable for those with fear of heights.',
  'Safety harness provided and mandatory. Follow all guide instructions.',
  ARRAY['Comfortable walking shoes', 'Binoculars', 'Camera', 'Water', 'Insect repellent'],
  ARRAY['English', 'Spanish'],
  ARRAY['adventure', 'nature', 'wildlife', 'canopy', 'eco-tourism']
),

-- Georgetown Colonial Heritage Walking Tour
(
  'Georgetown Colonial Heritage Walking Tour',
  'georgetown-heritage-tour',
  'Discover Georgetown''s rich colonial history through its stunning wooden architecture, including St. George''s Cathedral, City Hall, and the famous Stabroek Market.',
  (SELECT id FROM tourism_categories WHERE slug = 'history-heritage'),
  'tour',
  '2.5 hours',
  'easy',
  2,
  20,
  'All ages',
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Central Georgetown, starting at St. George''s Cathedral',
  'St. George''s Cathedral main entrance',
  '5926245555',
  '5926245555',
  'tours@georgetownheritage.gy',
  NULL,
  'Heritage Guyana Tours',
  'GTA-2024-003',
  3500,
  'Per person',
  'Professional guide, Historical insights, Photo opportunities, Water bottle',
  'Entrance fees to museums, Meals, Transportation',
  ARRAY['Year-round'],
  'Morning tours recommended to avoid afternoon heat',
  false,
  0,
  true,
  false,
  true,
  'Wheelchair accessible route available upon request.',
  'Sun protection recommended. Stay with group.',
  ARRAY['Comfortable walking shoes', 'Sun hat', 'Camera', 'Small umbrella'],
  ARRAY['English', 'Dutch', 'Portuguese'],
  ARRAY['history', 'culture', 'architecture', 'city-tour', 'photography']
),

-- Rupununi Savannah Wildlife Safari
(
  'Rupununi Savannah Wildlife Safari',
  'rupununi-wildlife-safari',
  'Explore the vast Rupununi savannahs, home to giant anteaters, giant river otters, jaguars, and over 400 bird species. Experience authentic Amerindian culture in local villages.',
  (SELECT id FROM tourism_categories WHERE slug = 'expeditions'),
  'tour',
  '4 days / 3 nights',
  'moderate',
  4,
  8,
  '16+',
  (SELECT id FROM regions WHERE slug = 'upper-takutu-upper-essequibo'),
  'Rupununi Savannah, Region 9',
  'Lethem Airport or Annai Village',
  '5927725555',
  '5927725555',
  'safari@rupununiadventures.gy',
  'www.rupununiadventures.gy',
  'Rupununi Trails',
  'GTA-2024-004',
  125000,
  'Per person (all-inclusive)',
  'All meals, Accommodation, Transportation, Guides, Village visits, Wildlife spotting tours',
  'Flights to Lethem, Alcoholic beverages, Personal items, Tips',
  ARRAY['Year-round'],
  'Dry season (October - April) for best wildlife viewing',
  true,
  7,
  true,
  true,
  true,
  'Basic fitness required for nature walks. Simple accommodation in eco-lodges.',
  'Malaria prevention recommended. Follow wildlife viewing guidelines.',
  ARRAY['Light clothing', 'Hat', 'Sunscreen', 'Insect repellent', 'Binoculars', 'Camera', 'Flashlight'],
  ARRAY['English', 'Portuguese'],
  ARRAY['wildlife', 'safari', 'culture', 'indigenous', 'adventure', 'multi-day']
),

-- Essequibo River Sunset Cruise
(
  'Essequibo River Sunset Cruise',
  'essequibo-sunset-cruise',
  'Cruise along South America''s third-largest river while enjoying a spectacular sunset. Spot river dolphins, caimans, and numerous bird species.',
  (SELECT id FROM tourism_categories WHERE slug = 'water-activities'),
  'activity',
  '3 hours',
  'easy',
  4,
  25,
  'All ages',
  (SELECT id FROM regions WHERE slug = 'essequibo'),
  'Essequibo River, departing from Bartica',
  'Bartica Stelling (Wharf)',
  '5926555555',
  '5926555555',
  'cruises@essequiboriver.gy',
  NULL,
  'River Adventures Guyana',
  'GTA-2024-005',
  6500,
  'Per person',
  'River cruise, Snacks and beverages, Wildlife guide, Life jackets',
  'Transportation to Bartica, Alcoholic drinks, Dinner',
  ARRAY['Year-round'],
  'Best from 4:30 PM for sunset viewing',
  true,
  1,
  true,
  false,
  false,
  'Suitable for all ages. Life jackets provided.',
  'Life jackets mandatory. Stay seated while boat is moving.',
  ARRAY['Camera', 'Light jacket', 'Sunglasses', 'Binoculars'],
  ARRAY['English'],
  ARRAY['river', 'sunset', 'relaxation', 'wildlife', 'photography']
),

-- Shell Beach Turtle Watching Expedition
(
  'Shell Beach Turtle Watching Expedition',
  'shell-beach-turtle-watching',
  'Witness endangered sea turtles nesting on pristine beaches. This conservation-focused tour includes education about marine turtle protection efforts.',
  (SELECT id FROM tourism_categories WHERE slug = 'nature-wildlife'),
  'tour',
  '2 days / 1 night',
  'moderate',
  2,
  10,
  '12+',
  (SELECT id FROM regions WHERE slug = 'barima-waini'),
  'Shell Beach Protected Area, Region 1',
  'Charity Airport or Georgetown (boat transfer)',
  '5926895555',
  '5926895555',
  'turtles@conservationguyana.org',
  'www.seaturtlesguyana.org',
  'Shell Beach Adventures',
  'GTA-2024-006',
  35000,
  'Per person',
  'Accommodation, Meals, Guided turtle watching, Conservation talk, Transportation from Charity',
  'Flights to Charity, Personal items, Tips',
  ARRAY['March', 'April', 'May', 'June', 'July', 'August'],
  'Peak nesting: April - July',
  true,
  14,
  true,
  false,
  true,
  'Beach walking at night required. Basic accommodation in village guesthouse.',
  'Red lights only during turtle watching. No flash photography.',
  ARRAY['Red flashlight', 'Insect repellent', 'Long pants', 'Rain jacket', 'Camera without flash'],
  ARRAY['English'],
  ARRAY['wildlife', 'conservation', 'turtles', 'beach', 'eco-tourism', 'night-tour']
),

-- Amerindian Village Cultural Experience
(
  'Amerindian Village Cultural Experience',
  'amerindian-village-experience',
  'Immerse yourself in indigenous culture at Surama Village. Learn traditional crafts, taste cassava bread, and participate in cultural performances.',
  (SELECT id FROM tourism_categories WHERE slug = 'culture'),
  'activity',
  '2 days / 1 night',
  'easy',
  2,
  12,
  'All ages',
  (SELECT id FROM regions WHERE slug = 'upper-demerara-berbice'),
  'Surama Village, North Rupununi',
  'Surama Village Centre',
  '5926775555',
  '5926775555',
  'visits@suramaecolodge.com',
  'www.suramaecolodge.com',
  'Surama Eco-Lodge',
  'GTA-2024-007',
  28000,
  'Per person',
  'Accommodation, All meals, Cultural activities, Village tour, Craft demonstration',
  'Transportation to Surama, Alcoholic beverages, Souvenirs',
  ARRAY['Year-round'],
  'Year-round',
  true,
  3,
  true,
  true,
  true,
  'Basic accommodation in traditional benabs. All fitness levels welcome.',
  'Respect local customs. Ask permission before photography.',
  ARRAY['Modest clothing', 'Walking shoes', 'Insect repellent', 'Camera', 'Small gifts for village'],
  ARRAY['English', 'Makushi'],
  ARRAY['culture', 'indigenous', 'traditional', 'crafts', 'community', 'authentic']
),

-- Guyana Birding Photography Tour
(
  'Guyana Birding Photography Tour',
  'birding-photography-tour',
  'Specialized tour for bird photographers targeting Guyana''s 800+ bird species including the Guianan Cock-of-the-rock, Harpy Eagle, and numerous endemic species.',
  (SELECT id FROM tourism_categories WHERE slug = 'bird-watching'),
  'tour',
  '5 days / 4 nights',
  'moderate',
  2,
  6,
  '18+',
  (SELECT id FROM regions WHERE slug = 'cuyuni-mazaruni'),
  'Multiple locations including Kaieteur, Iwokrama, and Atta Lodge',
  'Eugene F. Correia International Airport',
  '5926445555',
  '5926445555',
  'birds@guyanaphototours.com',
  'www.guyanaphototours.com',
  'Wilderness Explorers',
  'GTA-2024-008',
  185000,
  'Per person',
  'All accommodation, Meals, Expert birding guide, Transportation, Park fees',
  'International flights, Photography equipment, Alcoholic beverages, Tips',
  ARRAY['Year-round'],
  'October - April (dry season)',
  true,
  14,
  true,
  false,
  false,
  'Early morning starts. Moderate hiking required. Photography hides available.',
  'Quiet observation required. Camouflage clothing recommended.',
  ARRAY['Camera with telephoto lens', 'Binoculars', 'Field guide', 'Neutral colored clothing', 'Rain gear'],
  ARRAY['English'],
  ARRAY['birding', 'photography', 'wildlife', 'endemic-species', 'specialized']
),

-- Demerara Rum Distillery Tour
(
  'Demerara Rum Distillery Tour',
  'demerara-rum-tour',
  'Tour the historic Demerara Distillery, home of El Dorado rum. Learn about 300 years of rum-making tradition and enjoy premium tastings.',
  (SELECT id FROM tourism_categories WHERE slug = 'food-culinary'),
  'tour',
  '2 hours',
  'easy',
  4,
  20,
  '18+',
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Diamond, East Bank Demerara',
  'Demerara Distillery Main Gate',
  '5922655555',
  '5922655555',
  'tours@demeraradistillery.com',
  'www.theeldoradorumtour.com',
  'Demerara Distillers Limited',
  'GTA-2024-009',
  4500,
  'Per person',
  'Guided distillery tour, Rum tasting (5 varieties), Souvenir glass, Historical presentation',
  'Transportation, Meals, Rum purchases',
  ARRAY['Year-round'],
  'Monday to Friday, 9 AM - 3 PM',
  true,
  2,
  true,
  false,
  true,
  'Walking tour of production facility. Closed-toe shoes required.',
  'No smoking in production areas. Must be 18+ for tasting.',
  ARRAY['Closed-toe shoes', 'Camera', 'ID for age verification'],
  ARRAY['English'],
  ARRAY['culinary', 'rum', 'history', 'tasting', 'cultural']
),

-- Mount Roraima Expedition
(
  'Mount Roraima Expedition',
  'mount-roraima-expedition',
  'Trek to the summit of Mount Roraima, the inspiration for Arthur Conan Doyle''s "The Lost World". This challenging expedition crosses into Venezuela.',
  (SELECT id FROM tourism_categories WHERE slug = 'expeditions'),
  'tour',
  '8 days / 7 nights',
  'extreme',
  4,
  12,
  '18+',
  (SELECT id FROM regions WHERE slug = 'upper-takutu-upper-essequibo'),
  'Mount Roraima, Guyana-Venezuela-Brazil tri-border',
  'Lethem, Guyana',
  '5927445555',
  '5927445555',
  'expeditions@roaraimaadventures.com',
  'www.roaraimaexpeditions.gy',
  'Roraima Mountain Guides',
  'GTA-2024-010',
  250000,
  'Per person (all-inclusive)',
  'All camping equipment, Meals, Guides, Porters, Permits, Transportation from Lethem',
  'International flights, Personal gear, Travel insurance, Venezuelan visa',
  ARRAY['September', 'October', 'November', 'December', 'January', 'February', 'March'],
  'December - March (driest months)',
  true,
  30,
  true,
  false,
  false,
  'Excellent physical fitness required. High altitude trekking experience recommended.',
  'Comprehensive travel insurance mandatory. Medical clearance recommended.',
  ARRAY['Hiking boots', 'Warm clothing', 'Rain gear', 'Sleeping bag', 'Headlamp', 'Trekking poles', 'First aid kit'],
  ARRAY['English', 'Spanish', 'Portuguese'],
  ARRAY['adventure', 'trekking', 'extreme', 'mountain', 'expedition', 'bucket-list']
);

-- Insert some sample tourism photos for the experiences
INSERT INTO public.tourism_photos (experience_id, image_url, caption, photo_type, display_order, is_primary)
SELECT
  id,
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&h=800&fit=crop',
  'Majestic Kaieteur Falls',
  'cover',
  0,
  true
FROM tourism_experiences WHERE slug = 'kaieteur-falls-day-trip';

INSERT INTO public.tourism_photos (experience_id, image_url, caption, photo_type, display_order, is_primary)
SELECT
  id,
  'https://images.unsplash.com/photo-1511497584788-876760111969?w=1200&h=800&fit=crop',
  'Walking among the trees',
  'cover',
  0,
  true
FROM tourism_experiences WHERE slug = 'iwokrama-canopy-walkway';

INSERT INTO public.tourism_photos (experience_id, image_url, caption, photo_type, display_order, is_primary)
SELECT
  id,
  'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop',
  'Colonial architecture of Georgetown',
  'cover',
  0,
  true
FROM tourism_experiences WHERE slug = 'georgetown-heritage-tour';