-- Add More Rental Seed Data for Testing Search & Filters
-- This migration adds 6 more diverse rental properties with various amenities

-- Sample Property 7: WiFi + AC + Parking Apartment (for testing amenities filter)
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  address,
  location_details,
  bedrooms,
  bathrooms,
  max_guests,
  square_feet,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  is_featured,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'apartments'),
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Executive Studio with All Amenities',
  'executive-studio-all-amenities-georgetown',
  'Premium studio apartment with WiFi, AC, and secure parking. Perfect for business travelers. Walking distance to downtown Georgetown.',
  'apartment',
  '45 Water Street, Georgetown',
  'Near Stabroek Market, Central Georgetown',
  0, -- Studio
  1.0,
  2,
  500,
  120000,
  120000,
  '["wifi", "ac", "parking", "kitchen", "tv", "hot_water", "furnished", "security", "washer_dryer"]'::jsonb,
  '["water", "internet", "electricity"]'::jsonb,
  '["no_smoking", "no_pets", "quiet_hours"]'::jsonb,
  '5926007777',
  TRUE,
  TRUE,
  89,
  15
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Sample Property 8: WiFi Only Apartment (for testing amenities filter)
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  bedrooms,
  bathrooms,
  max_guests,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'apartments'),
  (SELECT id FROM regions WHERE slug = 'linden'),
  'Cozy 1BR Apartment with WiFi',
  'cozy-1br-apartment-wifi-linden',
  'Affordable 1-bedroom apartment with high-speed WiFi included. Great for remote workers and students.',
  'apartment',
  1,
  1.0,
  2,
  85000,
  85000,
  '["wifi", "kitchen", "hot_water", "furnished"]'::jsonb,
  '["water", "internet"]'::jsonb,
  '["no_smoking", "quiet_hours"]'::jsonb,
  '5926008888',
  TRUE,
  45,
  8
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Sample Property 9: AC + Parking House (for testing amenities filter)
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  bedrooms,
  bathrooms,
  max_guests,
  square_feet,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'houses'),
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Spacious 4BR House with AC & Parking',
  'spacious-4br-house-ac-parking-georgetown',
  'Large family home with AC in all bedrooms and parking for 2 vehicles. Perfect for families with cars.',
  'house',
  4,
  3.0,
  8,
  1800,
  280000,
  280000,
  '["ac", "parking", "kitchen", "tv", "hot_water", "yard", "furnished", "pool"]'::jsonb,
  '["water", "electricity"]'::jsonb,
  '["no_smoking", "no_parties"]'::jsonb,
  '5926009999',
  TRUE,
  123,
  19
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Sample Property 10: Budget Apartment (no premium amenities - for testing filters)
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  bedrooms,
  bathrooms,
  max_guests,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'apartments'),
  (SELECT id FROM regions WHERE slug = 'bartica'),
  'Budget-Friendly 2BR Apartment',
  'budget-2br-apartment-bartica',
  'Affordable 2-bedroom apartment. Basic amenities, perfect for budget-conscious renters.',
  'apartment',
  2,
  1.0,
  4,
  65000,
  65000,
  '["kitchen", "hot_water"]'::jsonb,
  '["water"]'::jsonb,
  '["no_smoking", "no_pets"]'::jsonb,
  '5926005555',
  TRUE,
  34,
  5
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Sample Property 11: Vacation Home with All Amenities
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  address,
  location_details,
  bedrooms,
  bathrooms,
  max_guests,
  square_feet,
  price_per_night,
  price_per_week,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  is_featured,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'vacation-homes'),
  (SELECT id FROM regions WHERE slug = 'lethem'),
  'Luxury Beach House - WiFi, AC, Parking',
  'luxury-beach-house-lethem',
  'Stunning beach house with all modern amenities. WiFi, AC throughout, secure parking, and private beach access. Perfect for vacations.',
  'vacation-home',
  'Ocean View Drive, Lethem',
  'Beachfront property with stunning ocean views',
  3,
  2.5,
  8,
  1500,
  15000,
  90000,
  350000,
  350000,
  '["wifi", "ac", "parking", "pool", "kitchen", "washer_dryer", "tv", "hot_water", "furnished", "security", "generator"]'::jsonb,
  '["water", "internet", "electricity"]'::jsonb,
  '["no_smoking", "no_parties", "quiet_hours"]'::jsonb,
  '5926006666',
  TRUE,
  TRUE,
  234,
  42
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);

-- Sample Property 12: Office Space with WiFi & AC
INSERT INTO rentals (
  landlord_id,
  category_id,
  region_id,
  name,
  slug,
  description,
  property_type,
  address,
  location_details,
  bathrooms,
  max_guests,
  square_feet,
  price_per_month,
  security_deposit,
  amenities,
  utilities_included,
  house_rules,
  whatsapp_number,
  is_approved,
  view_count,
  inquiry_count
)
SELECT
  (SELECT id FROM auth.users LIMIT 1),
  (SELECT id FROM rental_categories WHERE slug = 'office-spaces'),
  (SELECT id FROM regions WHERE slug = 'georgetown'),
  'Professional Office Suite - WiFi & AC',
  'professional-office-suite-georgetown',
  'Modern office space with high-speed WiFi, central AC, and parking. Perfect for startups and small businesses.',
  'office',
  '100 Camp Street, Georgetown',
  'Downtown Georgetown, near government offices',
  2.0,
  15,
  800,
  200000,
  200000,
  '["wifi", "ac", "parking", "kitchen", "furnished", "security", "generator"]'::jsonb,
  '["water", "internet", "electricity"]'::jsonb,
  '["no_smoking"]'::jsonb,
  '5926004444',
  TRUE,
  67,
  12
WHERE EXISTS (SELECT 1 FROM auth.users LIMIT 1);
